ExportToExcel/Models/ErrorViewModel.cs
using System;

namespace ExportToExcel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExportToExcel/Models/Shipper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExportToExcel.Models
{
    public class Shipper
    {
        public int ShipperID { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public bool? Aktifmi { get; set; }

    }
}

ExportToExcel/Controllers/ExportController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Data;
using ClosedXML.Excel;
using ExportToExcel.Context;
using ExportToExcel.Models;

namespace ExportToExcel.Controllers
{
    public class ExportController : Controller
    {
        private NortwindContext Context { get; }

        public ExportController(NortwindContext _context)
        {
            this.Context = _context;
        }
        public IActionResult Index()
        {
            List<Shipper> shippers=(from shipper in this.Context.Shippers.Take(10)
                                      select shipper).ToList();
            return View(shippers);
        }

        [HttpPost]
        public IActionResult Export()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[4]
            {
                new DataColumn("ShipperID"),
                new DataColumn("CompanyName"),
                new DataColumn("Phone"),
                new DataColumn("Aktifmi")
            });

            var shippers = from shipper in this.Context.Shippers.Take(10) select shipper;

            foreach (var shipper in shippers)
            {
                dt.Rows.Add(shipper.ShipperID, shipper.CompanyName, shipper.Phone, shipper.Aktifmi);
            }

            using(XLWorkbook wb=new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using(MemoryStream stream=new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Data.xlsx");
                }
            }
        }
    }
}

ExportToExcel/Controllers/HomeController.cs
using ExportToExcel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExportToExcel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExportToExcel/Views/Export/Index.cshtml
@using ExportToExcel.Models
@model IEnumerable<Shipper>


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <h4>Shippers</h4>
    <hr />
    <table >
        <tr>
            <th>ShipperID</th>
            <th>CompanyName</th>
            <th>Phone</th>
            <th>Aktifmi</th>
        </tr>

        @foreach (Shipper shipper in Model)
        {
            <tr>
                <td>@shipper.ShipperID</td>
                <td>@shipper.CompanyName</td>
                <td>@shipper.Phone</td>
                <td>@shipper.Aktifmi</td>
            </tr>
        }
    </table>
    <br />
    <br />
    <form method="post" asp-controller="Export" asp-action="Export">
        <input type="submit" value="Export To Excel" />
    </form>
</body>
</html>

ExportToExcel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExportToExcel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExportToExcel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExportToExcel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ExportToExcel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>